version: "3"
services:
  builder:
    stdin_open: true
    tty: true
    privileged: true
    build:
      context: .
    command: /bin/bash
    volumes:
      - ./:/usr/src:Z
      - /dev/:/dev/
